# Image de base
FROM node:20-alpine
# Dossier de travail
WORKDIR /app
# Copier les fichiers de dépendances
COPY package*.json ./
# Installer dépendances
RUN npm install
# Copier le code source
COPY . .
# Exposer le port du service
EXPOSE 3002
# Commande de démarrage
CMD ["npm", "start"]